#[derive(Copy, Clone, Debug, Eq, PartialEq)]
enum PlaybackOrigin {
    Standalone,
    Queue,
}

struct PlaybackSession {
    origin: PlaybackOrigin,
    config: MpvSessionConfig,
    reporter: SessionReporter,
    event_tx: mpsc::Sender<PlayerEvent>,
    status: Arc<Mutex<PlayerStatus>>,
    subtitle_prefs: Arc<Mutex<SubtitlePrefs>>,
    is_queue_mode: Arc<AtomicBool>,
    server_url: String,
    token: String,
    queue: PlaybackQueue,
    ext_sub_urls: Vec<String>,
    // loop state
    current_idx: usize,
    forced_slot_id: Option<QueueSlotId>,
    quit_at: Option<Instant>,
    last_seek_at: Option<Instant>,
    last_valid_pos: i64,
    tracks_initialized: bool,
    pending_load: u8,
    pending_initial_jump: bool,
    stop_reported: bool,
    stop_report_accepted: bool,
    stopped_event_sent: bool,
    mark_played_id: Option<String>,
    osd_title: String,
    last_mouse_osd: Option<Instant>,
    pending_resume_secs: Option<f64>,
    series_id: String,
    season: i64,
    episode: i64,
    next_up_fired: bool,
    next_up_armed: bool,
    queue_next_up_fired: bool,
    queue_next_up_armed: bool,
    next_up_jump: bool,
    stopped_near_end: bool,
    shutdown_report_timeout: Arc<Mutex<Option<Duration>>>,
    startup_pause_release_pending: bool,
    startup_pause_events_to_skip: u8,
    // intro
    intro_start: i64,
    intro_end: i64,
    intro_show: bool,
    intro_hide: bool,
}
