//! The closed surface identity set (change `theme-slot-model`, design D4).
//!
//! [`Surface`] is generated by `declare_surfaces!` from one variant list, so a
//! new variant cannot be added without the table's `slots` failing to compile
//! until it is placed. Each surface's `(resting, focused)` slot pair lives in
//! `surface_table` and the one resolver in `surface_resolve`.
//!
//! Only [`Surface`], [`HINT_CHIPS`] and the resolver's `surface_colors` are
//! crate-visible, so a screen cannot resolve anything but a named surface
//! through the resolver.
//!
//! The identity names are the archived `unify-surface-colour` change's,
//! verbatim (D7): they are the reviewed vocabulary.

/// Declares the closed `Surface` set from one variant list, so a new variant
/// cannot be added without the table's `slots` failing to compile until it is
/// placed.
macro_rules! declare_surfaces {
    ($($variant:ident),+ $(,)?) => {
        /// A rendered-surface identity: a structural position in the layout,
        /// not a screen. The same position in a different screen or provider
        /// is the same identity; what the surface holds is content.
        #[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
        pub enum Surface {
            $($variant),+
        }

        #[cfg(test)]
        impl Surface {
            /// Every surface, in declaration order (`docs/palette.json` generator).
            pub(crate) const ALL: &[Surface] = &[$(Surface::$variant),+];
        }
    };
}

declare_surfaces!(
    // --- column/pane: the surface a content body sits on ---
    QueueColumn,
    LibraryColumn,
    HeroPane,
    // --- content body: a focusable content region ---
    LibraryPanel,
    QueuePanel,
    MainContentBox,
    PlaybackPanel,
    // The Queue-only playback strip: a mode-driven chrome-band appearance, not
    // a focus-driven one (see `surface_table`'s row doc).
    QueueOnlyPlaybackPanel,
    SidebarBody,
    // --- recess: a non-focusable inset inside a content body ---
    PlaybackStatusPill,
    ArtworkPlaceholder,
    ArtworkLoadingPlaceholder,
    // --- chrome band: non-focusable structural chrome ---
    // The queue card's visualizer fills the queue playback panel's own band,
    // so it carries that band's value rather than following panel focus.
    QueueCardVisualizer,
    StatusBar,
    StatusBarPill,
    QueuePanelBand,
    SidebarBand,
    TabBar,
    PillRow,
    PillChip,
    PillChipSelected,
    // The queue's selected scope pill: its aqua is the Direct-remote
    // indicator (`CONTEXT.md`, "Direct remote control"), not the library
    // pill's selected blue, so it is its own row rather than a variant of
    // `PillChipSelected`.
    QueueScopePillSelected,
    PillRowGap,
    // --- fills that replaced roles (design D5): one concept takes one
    // identity, so the selection bar, the fixed list stripes and the former
    // role-driven fills are surface rows ---
    SelectedRow,
    ListStripe,
    WorkspaceStripe,
    CreditsStripe,
    TransportRow,
    // --- popup: an overlay frame and its dim backdrop ---
    PopupBorder,
    PopupFrame,
    ModalButton,
    // The Library Hero overlay's display-only hint chips, rotated by chip
    // index (`HINT_CHIPS`).
    HintChip0,
    HintChip1,
    HintChip2,
);

/// The Library Hero overlay's display-only hint chips' fills, rotated by chip
/// index (foam, yellow, orange, repeating). A surface set of its own rather
/// than borrowed text roles: these are chip *surfaces*, and a text-colour edit
/// must not move them.
pub const HINT_CHIPS: [Surface; 3] = [Surface::HintChip0, Surface::HintChip1, Surface::HintChip2];
