pub(in crate::app) mod album_cursor;
pub(in crate::app) mod app_init;
pub(in crate::app) mod app_struct;
pub(in crate::app) mod bootstrap;
pub(in crate::app) mod construct;
pub(in crate::app) mod context_menu_capabilities;
pub(in crate::app) mod library_position;
pub(in crate::app) mod library_route;
pub(in crate::app) mod music_artist_detail;
pub(in crate::app) mod music_grouping;
pub(in crate::app) mod panel_focus;
pub(in crate::app) mod panel_targets;
pub(in crate::app) mod playback_target;
pub(in crate::app) mod projection;
pub(in crate::app) mod queue_owner;
pub(in crate::app) mod queue_scope;
pub(in crate::app) mod remote_slot;
pub(in crate::app) mod remote_tracking;
pub(in crate::app) mod runtime_channels;
pub(in crate::app) mod service_runtime;
pub(in crate::app) mod service_setup;

pub(in crate::app) mod events;
pub(crate) mod home_latest;
pub(in crate::app) mod playback;
pub(in crate::app) mod player_tab;
pub mod types;
