[package]
name = "mbv-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Service runtime state and application logging for mbv."
readme = "../../README.md"

[lints]
workspace = true

[features]
test = []

[dependencies]
log.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-log.workspace = true
time.workspace = true

[dev-dependencies]
rstest.workspace = true
mbv-audiobookshelf = { path = "../mbv-audiobookshelf" }
mbv-emby = { path = "../mbv-emby" }
mbv-config = { path = "../mbv-config", features = ["test"] }
mbv-queue = { path = "../mbv-queue" }
ureq.workspace = true
serde_json.workspace = true
libmpv2.workspace = true
rust_cast.workspace = true
