[package]
name = "mbv-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Service runtime state and application logging for mbv."
readme = "../../README.md"

[lints]
workspace = true

[dependencies]
log.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", default-features = false, features = ["registry", "std"] }
tracing-log = "0.2"
time.workspace = true

[dev-dependencies]
rstest.workspace = true
mbv-audiobookshelf = { path = "../mbv-audiobookshelf" }
mbv-emby = { path = "../mbv-emby" }
mbv-config = { path = "../mbv-config" }
mbv-queue = { path = "../mbv-queue" }
ureq.workspace = true
serde_json.workspace = true
libmpv2.workspace = true
rust_cast = "0.21"
