[package]
name = "mbv-images"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Image caching and terminal image protocol support for mbv."
readme = "../../README.md"

[features]
test = []

[lints]
workspace = true

[dependencies]
ab_glyph.workspace = true
num-traits.workspace = true
ratatui.workspace = true
ratatui-image = { workspace = true, features = ["crossterm"] }
image.workspace = true
tracing.workspace = true
foldhash.workspace = true

[dev-dependencies]
rstest.workspace = true
