pub(in crate::app) mod card;
pub(in crate::app) mod chrome_player_context;
pub(in crate::app) mod chrome_status;
pub(in crate::app) mod detail;
pub(in crate::app) mod list_context;
pub(in crate::app) mod music_wide;
pub(in crate::app) mod queue;
pub(in crate::app) mod tv_wide;
pub(in crate::app) mod visualizer;
